config/routes.rb
Rails.application.routes.draw do

  resources :categories

  devise_for :users
  get 'admin' => 'admin#index'
  controller :sessions do
    delete 'logout' => :destroy
  end
  

  devise_scope :user do
    get '/login' => 'devise/sessions#new'
  end

  get 'sessions/create'
  get 'sessions/destroy'

  resources :users

  get 'store/index'
  
  resources :products do
    get :who_bought, on: :member
    put :show, on: :member
  end

  resources :line_items do
    post 'decrement', on: :member
  end

  resources :orders
  resources :line_items
  resources :carts

root 'store#index', as: 'store', via: :all

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :orders, through: :line_items
  belongs_to :category
  before_destroy :ensure_not_referenced_by_any_line_item

  validates :title, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :image_url, format: {
    with: %r{\.(gif|jpg|png)\Z}i,
    message: 'Must be a URL for GIF, PNG, JPG image.'
  }
  validates :title, length: {minimum: 10, too_short: 'Must be at least 10 characters long'}

  def self.latest
    Product.order(:updated_at).last
  end

  private
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items Present')
        return false
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include CurrentCart

  before_filter :authenticate_user!, except: [:show]

  before_action :set_cart, only: [:new, :create, :show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.joins("LEFT JOIN categories on products.category_id = categories.id").order("LOWER(name)","LOWER(title)", "price").paginate(page: params[:page], per_page: 4)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end
  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        flash[:notice] = 'Product was not created.'
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
        if @product.valid? && @product.update(product_params)
          format.html { redirect_to @product, notice: 'Product was successfully updated.' }
          format.json { render status: :ok, location: @product }
        else
          flash[:notice] = 'Product was not valid'
          format.html { render :edit }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    message = 'Product was not destroyed.'
    if @product.valid?
      @product.destroy
      if @product.destroyed?
        message = 'Product was successfully destroyed.'
      end
    end
    
    respond_to do |format|
      format.html { redirect_to products_url, notice: message }
      format.json { head :no_content }
    end
  end

  def who_bought
    @product = Product.find(params[:id])
    @latest_order = @product.orders.order(:updated_at).last
      if stale?(@latest_order)
        respond_to do |format|
          format.atom
        end
      end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      if Product.exists?(params[:id])
        @product = Product.find(params[:id])
      else
        respond_to do |format|
          format.html { redirect_to products_url, notice: 'No such product exists' }
          format.json { render :index, status: :ok, location: @product }
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :category_id, :image_url, :price)
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 6 %>
  </div>
  
  <div class="field">
    <%= f.label :category_id %><br>
	 <%= f.select :category_id, Category.pluck(:name, :id) %>
  </div>

  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing Products</h1>
<%= will_paginate @products %>
<table>
  <% @products.each do |product| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <td><%= image_tag(product.image_url, class: 'list_image') %> </td>
      <td class="list_description">
        <dl>
          <dt><%= product.title %></dt>
            <dd><%= truncate(strip_tags(product.description), length: 80) %></dd>
			<dd>Genre: <%= product.category.try(:name)%>
        </dl>
      </td>      <td class="list_actions">
        <%= link_to 'Show', product %><br/>
        <%= link_to 'Edit', edit_product_path(product) %><br/> <%= link_to 'Destroy', product, method: :delete,
            data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
<% end %>
</table>
<br/>

<%= link_to 'New Product', new_product_path %>
<%= will_paginate @products %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= sanitize(@product.description) %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category.try(:name) %>
</p>

<% unless session[:user_id].nil? %>
<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>
<% end %>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Add', line_items_path(product_id: @product), method: :post, remote: true %>
<% unless session[:user_id].nil? %>
| <%= link_to 'Edit', edit_product_path(@product) %>
<% end %>
| <%= link_to 'Back', store_path %>