config/routes.rb
Rails.application.routes.draw do

  resources :categories

  devise_for :users
  get 'admin' => 'admin#index'
  controller :sessions do
    delete 'logout' => :destroy
  end
  

  devise_scope :user do
    get '/login' => 'devise/sessions#new'
  end

  get 'sessions/create'
  get 'sessions/destroy'

  resources :users

  get 'store/index'
  
  resources :products do
    get :who_bought, on: :member
    put :show, on: :member
  end

  resources :line_items do
    post 'decrement', on: :member
  end

  resources :orders
  resources :line_items
  resources :carts

root 'store#index', as: 'store', via: :all

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paraprog Books Online Store</title>
  <%= stylesheet_link_tag    'application', media: 'all',
    'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class = '<%= controller.controller_name %> container-fluid'>
  <div id = 'banner' class = 'row'>
    <!-- <%= form_tag store_path, class: 'locale collapse navbar-collapse navbar-ex1-collapse' do %>
      <%= select_tag 'set_locale',
            options_for_select(LANGUAGES, I18n.locale.to_s),
            onchange: 'this.form.submit()' %>
      <%= submit_tag 'submit' %>
      <%= javascript_tag "$('.locale input').hide()" %>
    <% end %> -->
    <%= image_tag("logo.png") %>
    <%= page_title %>
  </div>
  <div id = 'columns' class = 'row'>
    <div id = 'side' class = 'nav navbar-nav side-nav'>
          <% if @cart %>
            <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
              <%= render @cart %>
            <% end %>
          <% end %>

        <ul>
          <li><%= link_to t('.home'), store_path %></li>
          <li><a href = "http://www..../faq"><%= t('.questions')%></a></li>
          <li><a href = "http://www..../news"><%= t('.news')%></a></li>
          <li><a href = "http://www..../contact"><%= t('.contact')%></a></li>
          <li><%= unless user_signed_in? then link_to t('.login'), login_path  end%></li>
        </ul>
        <% if user_signed_in? %>
        <ul>
		  <li><%= link_to 'Categories', categories_path %></li>
          <li><%= link_to 'Orders', orders_path %></li>
          <li><%= link_to 'Products', products_path %></li>
          <li><%= link_to 'Users', users_path %></li>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% end %>
        </ul>
        <span class = 'myAdds'>Current Date:<br/> <%= DateTime.now.to_date %></span>
        <span class = 'myAdds'><br/>Current Time:<br/> <%= Time.now.strftime("%I:%M %p") %></span>
    </div>
    <div id = 'main'>
	<% if notice %>
      <p class="notice"><%= notice %></p>
	<% end %>
	<% if alert %>
      <p class="alert"><%= alert %></p>
	<% end %> 
      <%= yield %>
    </div>
  </div>
</body>
</html>